# Generated by Django 5.0.1 on 2024-02-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makepassword', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savepassword',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='savepassword',
            name='platform',
            field=models.CharField(max_length=30),
        ),
    ]
